# Generated by Django 4.2.1 on 2023-06-19 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_userprofile_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='reservation_count',
            field=models.IntegerField(default=0),
        ),
    ]
