# Generated by Django 4.2.1 on 2023-06-19 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_userprofile_reservation_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='address',
            field=models.CharField(default='Moorroco', max_length=200),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(default='0600000000', max_length=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(default='photos/profilepics/default_profile_pic.png', upload_to='photos/profilepics/%y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='typee',
            field=models.CharField(choices=[('user', 'user'), ('server', 'server')], default='user', max_length=100),
        ),
    ]
