# Generated by Django 4.2.1 on 2023-05-22 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(upload_to='photos/%y/%m%d')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categories', models.CharField(choices=[('burger', 'burger'), ('pizza', 'pizza'), ('salade', 'salade'), ('tacos', 'tacos'), ('sandwich', 'sandwich')], max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
